In [67]:
import pandas as pd

In [68]:
city = ['bangladesh', 'singapur', 'astraliya']

In [69]:
df = pd.DataFrame(city, columns=['city in asia'], index=['c1', 'c2', 'c3'])

In [70]:
df

   city in asia
c1   bangladesh
c2     singapur
c3    astraliya

In [71]:
type(city)

list

In [72]:
city2 = ['dhaka', 'sylet', 'chittagang']

In [73]:
df2 = pd.DataFrame(zip(city, city2), columns=['c1', 'c2'], index=['t1', 't2', 't3'])

In [77]:
df2

            c1          c2
t1  bangladesh       dhaka
t2    singapur       sylet
t3   astraliya  chittagang